# Generated by Django 6.0.6 on 2026-06-17 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="service",
            old_name="name",
            new_name="title",
        ),
        migrations.RemoveField(
            model_name="service",
            name="price_start_from",
        ),
        migrations.AlterField(
            model_name="gallery",
            name="is_featured",
            field=models.BooleanField(
                default=False,
                help_text="Centang jika gambar ini ingin ditampilkan sebagai unggulan di halaman utama (home page).",
            ),
        ),
        migrations.AlterField(
            model_name="herobanner",
            name="button_text",
            field=models.CharField(
                help_text="Teks tombol CTA (contoh: Pesan Sekarang, Hubungi Kami)",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="herobanner",
            name="button_url",
            field=models.URLField(
                help_text="Link tujuan tombol CTA (contoh: https://wa.me/628xxx atau https://domain.com/page)",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="image",
            field=models.ImageField(
                help_text="Gunakan gambar kotak (1:1) atau landscape ringan (4:3). Tampilkan makanan atau packaging layanan.",
                upload_to="services/",
            ),
        ),
        migrations.AlterField(
            model_name="sitesetting",
            name="favicon",
            field=models.ImageField(
                blank=True,
                help_text="Ikon kecil website untuk browser tab. Gunakan gambar persegi (32x32 atau 48x48 px), format PNG atau ICO.",
                null=True,
                upload_to="settings/favicon/",
            ),
        ),
        migrations.AlterField(
            model_name="sitesetting",
            name="logo",
            field=models.ImageField(
                help_text="Logo utama perusahaan. Disarankan gunakan gambar horizontal.",
                upload_to="settings/logo/",
            ),
        ),
    ]
