# Generated by Django 6.0.6 on 2026-06-18 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("public", "0002_rename_name_service_title_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Testimonial",
        ),
    ]
