# Generated by Django 6.0.6 on 2026-06-18 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public", "0004_about_companyvalue"),
    ]

    operations = [
        migrations.AlterField(
            model_name="about",
            name="image",
            field=models.ImageField(
                default="defaults/default.webp",
                help_text="Disarankan ukuran foto tidak lebih dari 200 KB (WebP lebih baik).",
                upload_to="about/",
            ),
        ),
        migrations.AlterField(
            model_name="gallery",
            name="image",
            field=models.ImageField(
                default="defaults/default.webp",
                help_text="Disarankan ukuran foto tidak lebih dari 100 KB (WebP lebih baik).",
                upload_to="gallery/",
            ),
        ),
        migrations.AlterField(
            model_name="herobanner",
            name="image",
            field=models.ImageField(
                default="defaults/default.webp",
                help_text="Disarankan ukuran foto tidak lebih dari 200 KB (WebP lebih baik).",
                upload_to="hero/",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="image",
            field=models.ImageField(
                default="defaults/default.webp",
                help_text="Disarankan ukuran foto tidak lebih dari 100 KB (WebP lebih baik). Gunakan gambar kotak (1:1) atau landscape ringan (4:3).",
                upload_to="services/",
            ),
        ),
        migrations.AlterField(
            model_name="sitesetting",
            name="logo",
            field=models.ImageField(
                default="defaults/default.webp",
                help_text="Logo utama perusahaan. Disarankan gunakan gambar horizontal.",
                upload_to="settings/logo/",
            ),
        ),
    ]
