# Generated by Django 6.0.6 on 2026-06-18 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public", "0005_alter_about_image_alter_gallery_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesetting",
            name="google_maps_embed_url",
            field=models.URLField(
                blank=True,
                help_text="URL Google Maps Embed (src iframe). Contoh: https://www.google.com/maps/embed?pb=...Kosongkan jika tidak ingin menampilkan peta.",
            ),
        ),
    ]
