# Generated by Django 6.0.6 on 2026-06-18 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public", "0006_sitesetting_google_maps_embed_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesetting",
            name="operating_hours",
            field=models.CharField(
                blank=True,
                help_text="Jam operasional perusahaan. Contoh: Senin - Sabtu, 08.00 - 17.00 WIB",
                max_length=255,
            ),
        ),
    ]
