# Generated by Django 6.0.6 on 2026-06-19 08:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public", "0007_sitesetting_operating_hours"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sitesetting",
            options={
                "verbose_name": "Site Setting",
                "verbose_name_plural": "Site Setting",
            },
        ),
        migrations.RemoveField(
            model_name="sitesetting",
            name="address",
        ),
        migrations.RemoveField(
            model_name="sitesetting",
            name="google_maps_embed_url",
        ),
        migrations.RemoveField(
            model_name="sitesetting",
            name="operating_hours",
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="address_country",
            field=models.CharField(default="ID", max_length=2),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="address_locality",
            field=models.CharField(
                default="", help_text="Kota/Kabupaten.", max_length=100
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="address_region",
            field=models.CharField(default="", help_text="Provinsi.", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="closing_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="google_business_profile_url",
            field=models.URLField(
                blank=True,
                help_text="Link listing Google Business Profile, dipakai di Schema sameAs.",
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="opening_days",
            field=models.CharField(
                blank=True,
                help_text="Kode hari dipisah koma sesuai BusinessDay, contoh: MO,TU,WE,TH,FR,SA",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="opening_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="postal_code",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="street_address",
            field=models.CharField(
                default="", help_text="Contoh: Jl. Merdeka No. 5.", max_length=255
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="sitesetting",
            name="phone",
            field=models.CharField(
                max_length=30,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Format nomor telepon tidak valid.",
                        regex="^\\+?[0-9\\-\\s]{8,20}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="sitesetting",
            name="whatsapp_number",
            field=models.CharField(
                max_length=30,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Isi nomor WhatsApp tanpa tanda +, spasi, atau strip. Contoh: 6281234567890",
                        regex="^[0-9]{10,15}$",
                    )
                ],
            ),
        ),
    ]
