# Generated by Django 6.0.6 on 2026-06-19 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "public",
            "0008_alter_sitesetting_options_remove_sitesetting_address_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="about",
            name="title",
        ),
        migrations.AddField(
            model_name="about",
            name="about_image_alt",
            field=models.CharField(
                blank=True,
                help_text="Deskripsi singkat foto ini, contoh: Tim dapur menyiapkan hidangan catering. Untuk aksesibilitas dan SEO gambar.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="sitesetting",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Buka Google Maps, tahan/tap lama titik lokasi sampai muncul pin merah, maka akan muncul koordinat dikotak pencarian. Angka pertama (sebelum koma) adalah latitude, isi di sini.",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sitesetting",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Angka kedua (setelah koma) dari hasil copy Google Maps, isi di sini sebagai longitude.",
                max_digits=9,
                null=True,
            ),
        ),
    ]
