# Generated by Django 6.0.6 on 2026-06-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public", "0009_remove_about_title_about_about_image_alt_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="herobanner",
            name="button_text",
        ),
        migrations.RemoveField(
            model_name="herobanner",
            name="button_url",
        ),
        migrations.AddField(
            model_name="herobanner",
            name="image_alt",
            field=models.CharField(
                blank=True,
                help_text="Deskripsi foto ini untuk aksesibilitas dan SEO, contoh: Hidangan nasi kotak Dapur Nusantara Catering. Kosongkan untuk pakai nama bisnis sebagai fallback.",
                max_length=255,
            ),
        ),
    ]
