# Generated by Django 6.0.6 on 2026-06-19 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public", "0010_remove_herobanner_button_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="image_alt",
            field=models.CharField(
                blank=True,
                help_text="Deskripsi foto ini. Kosongkan jika foto memang persis menggambarkan nama layanan (otomatis pakai judul layanan).",
                max_length=255,
            ),
        ),
    ]
