# Generated by Django 6.0.6 on 2026-06-19 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public", "0011_service_image_alt"),
    ]

    operations = [
        migrations.AddField(
            model_name="gallery",
            name="image_alt",
            field=models.CharField(
                blank=True,
                help_text="Deskripsi foto ini. Kosongkan jika foto memang persis menggambarkan nama layanan (otomatis pakai judul layanan).",
                max_length=255,
            ),
        ),
    ]
